### ISSUE TITLE
Update  graph window when data file change

### ISSUE THREAD

**Issue by pgoldbronn** [thelfer/tfel-plot#1]
Actualy, when we do a graphical plot, for exemple tplot data.txt -u 2:5, if data.txt is replaced by another file (with same name), tplot could not take care of it and nothing is draw.

It'll be fun if tplot could switch to this new file and draw this new data.

**Comment by thelfer** [comment]
Hi Patrick,
Indeed the qt class to wath a file is based on the inode of the file: it cannot track the fact the file has been deleted and that another file with the same name has been created. I will try to see if this can be improved.
Regards,
Thomas Helfer

**Comment by thelfer** [comment]
Hi Patrick,
this shall be fixed now. Let me know if it works for you.
Thomas

**Comment by pgoldbronn** [comment]
Great, it works !
