### ISSUE TITLE
get strings in first line as legend name

### ISSUE THREAD

**Issue by pgoldbronn** [thelfer/tfel-plot#2]
With a csv file type, tplot don't take care of first line column name if they are presient. It does only ifline begin with comment symbol '#'.

For exemple 
```
TIME RADIUS TEMPERATURE
1 2.5 300
2 2.6 400
3 2.8 550
4 3.0 600
5 3.5 620
```

`tplot exemple.txt -u 1:2 exemple.txt -u 1:3`

We must see RADIUS and TEMPERATURE as legend key

**Comment by thelfer** [comment]
This shall be good now.
