### ISSUE TITLE
How to specify separator character ure in file

### ISSUE THREAD

**Issue by pgoldbronn** [thelfer/tfel-plot#4]
tplot take care of space as column separator.

If we have other separator as ',' or ';' (or tab ?) we could not plot values. It wiould be nice if we could specify a value for separator like option `--separator ';'` (ou `-s ';'`)

For example csv file
```
TIME;RADIUS 1;RADIUS 2
1; 2.5 ; 2.5
2;2.6; 3.5
3;3.5 ;4.5
4   ;    5.5;6.0
5;5.1;8.0
```
tplot example.txt -s ';' -u 1:2 example.txt -s ';' -u 1:3

**Comment by thelfer** [comment]
You can now use the following syntax:

~~~~
tplot cvs:test.csv -u ...
~~~~

Here cvs refers to a file format where the data are separated by a comma or a semi-colon (In the current implementation, you can mix both).

**Comment by pgoldbronn** [comment]
File type is csv, isn't it ?
That doesn't work

**Comment by thelfer** [comment]
Can you update and try again ?

**Comment by pgoldbronn** [comment]
Great ! it works fine.
